[package]
name = "vsb"
version = "0.1.0"
authors = ["UE2020 <ttmmiizz101@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.10.0"
cgmath = "0.18.0"
lyon = "0.17.5"
